name: Update AoC Badges
on:
  schedule:
    - cron: "6 5 1-25 12 *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1751464
          session: ${{ secrets.AOC_SESSION_ID }}
          year: 2024
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
